-- Migrazione iniziale: crea le tabelle di utenti, ruoli e documenti.
-- Eseguita automaticamente da Flyway all'avvio dell'applicazione.
-- I tipi sono allineati a quelli attesi da Hibernate (ddl-auto: validate).

-- ------------------------------------------------------------------
-- Utenti
-- ------------------------------------------------------------------
CREATE TABLE utente (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    password      VARCHAR(255) NOT NULL,
    nome_completo VARCHAR(150) NOT NULL,
    attivo        BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Ruoli associati a ciascun utente (relazione uno-a-molti tramite @ElementCollection)
CREATE TABLE utente_ruolo (
    utente_id BIGINT      NOT NULL,
    ruolo     VARCHAR(20) NOT NULL,
    CONSTRAINT fk_utente_ruolo_utente
        FOREIGN KEY (utente_id) REFERENCES utente (id) ON DELETE CASCADE
);

-- ------------------------------------------------------------------
-- Documenti
-- ------------------------------------------------------------------
CREATE TABLE documento (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titolo             VARCHAR(200) NOT NULL,
    contenuto          TEXT,
    stato              VARCHAR(20)  NOT NULL,
    numero_protocollo  VARCHAR(50),
    proprietario       VARCHAR(100) NOT NULL,
    data_creazione     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    data_aggiornamento TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version            BIGINT       NOT NULL DEFAULT 0
);

-- Indici per le ricerche piu frequenti
CREATE INDEX idx_documento_proprietario ON documento (proprietario);
CREATE INDEX idx_documento_stato ON documento (stato);
