-- Tabella per i refresh token: token opachi e revocabili, lato server.
-- A differenza dell'access token (JWT stateless), il refresh token e
-- persistito cosi da poterlo invalidare (logout, rotazione, compromissione).

CREATE TABLE refresh_token (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token     VARCHAR(100) NOT NULL UNIQUE,
    username  VARCHAR(100) NOT NULL,
    scadenza  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revocato  BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_refresh_token_username ON refresh_token (username);
