-- Tabella outbox per la pubblicazione affidabile degli eventi (pattern Outbox).
-- L'evento viene scritto qui nella STESSA transazione del cambiamento di business;
-- un publisher schedulato lo invia poi a Kafka e lo marca come pubblicato.

CREATE TABLE outbox_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo          VARCHAR(50)  NOT NULL,
    aggregate_id  VARCHAR(100),
    topic         VARCHAR(200) NOT NULL,
    chiave        VARCHAR(200),
    payload       TEXT         NOT NULL,
    creato_il     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    pubblicato    BOOLEAN      NOT NULL DEFAULT FALSE,
    pubblicato_il TIMESTAMP(6) WITH TIME ZONE
);

-- Indice per recuperare velocemente gli eventi ancora da pubblicare
CREATE INDEX idx_outbox_da_pubblicare ON outbox_event (pubblicato, id);
